name: Publish Docker image
on:
  push:
    branches: [ master, main ]
    tags: [ "*" ]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    if: ${{ github.repository_owner == 'weso' }} # Do not run in forks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_TOKEN }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GitHub Container Registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/weso/rdfshape-api:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
