name: Publish OSS Sonatype
on:
  push:
    branches: [ master, main ]
    tags: [ "*" ]

jobs:
  publish:
    if: ${{ github.repository_owner == 'weso' }} # Do not run in forks
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        scala: [ 2.12.13 ]
        java: [ adopt@1.11 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
